### ISSUE TITLE
Error Reformatting

### ISSUE THREAD

**Issue by idkjs** [kgoggin/graphql-codegen-reason#1]
Ran some random schemas to check it out. Great project, sir. Kept trying stuff until I got an error. Finally got one with this [SpaceX schema](https://github.com/swcarlosrj/SpaceX-API/tree/master/src)

Steps:
1. Generate the schema with `npx fetch-graphql-schema https://yv004pqnq9.sse.codesandbox.io/graphql -o schema.graphql -r`

```js
schema: ./schema.graphql
generates:
  GraphQLTypes3.re:
    plugins:
      - reason-client
    config:
      scalars:
        "DateTime": "string"
```
Run: `[master*]node_modules/.bin/gql-gen`

Output. 
```sh
server [master*]node_modules/.bin/gql-gen
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate GraphQLTypes3.re
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        → 1685: <syntax error>


  Found 1 error

   ✖ GraphQLTypes3.re
    [object Object]
```

How do we render that object object so we can chase it down?

[schema.graphql gist](https://gist.github.com/idkjs/d63bffd88560e55fe60d92cc450d26fb)

Thanks. And thanks for sharing.

**Comment by kgoggin** [comment]
@idkjs Thanks so much for testing it out for me! This error turned out to be due to the SpaceX schema having field names that were reserved words in Reason (specifically `end` and `class`). I updated the list of these and was able to get it to build!

For the error formatting: I'd originally been running `parseRE` and `printRE` on the output of the codegen, which works essentially like `refmt` to prettify the generated code, but it'll fail if there's a syntax error. Right now I've taken that check out so that the codegen will always "work", but the result might have Reason errors. 

I'm not sure of the best way to address this moving forward, but I'll look into if there's a better way to output the error from `parseRE` - it seems pretty nice to catch that stuff at generation time, I think?

Really appreciate you helping me kick the tires on this! I'm mostly testing it against the non-trivial schema I'm working with at my day job but it does seem really helpful to throw some other tests at it as well... I wonder if it'd even be worth adding some to the test suite somehow?

**Comment by idkjs** [comment]
I just tried running this same test again and getting this error:
[reproduction](https://github.com/idkjs/graphql-codegen-reason-test)

```
codegen-test node_modules/.bin/gql-gen  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate src/GraphQLTypes.re
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        → Unable to find template plugin matching reason-client


  Found 1 error


   ✖ src/GraphQLTypes.re
    Unable to find template plugin matching 'reason-client'
    Install one of the following packages:


    - graphql-codegen-reason-client
    - graphql-codegen-reason-client-template
    - codegen-reason-client
    - codegen-reason-client-template
    - reason-client


Something went wrong
➜  codegen-test 
```

You are probably just moving things around.
